//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesReunions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reunions()
        {
            this.reunion_utilisateur = new HashSet<reunion_utilisateur>();
        }
    
        public string Titre { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Heures { get; set; }
        public string Lieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reunion_utilisateur> reunion_utilisateur { get; set; }
        public virtual Salles Salles { get; set; }
    }
}
